### ISSUE TITLE
Open pull request on GitHub

### ISSUE THREAD

**Issue by xster** [Axosoft/vscode-gitlens#1069]
I'd like to propose a different angle on https://github.com/eamodio/vscode-gitlens/issues/623. 

Generally, all the context, discussion and related issues are in the GitHub pull request page rather than on the commit page itself. 

I get that it's generally a click away but since I do it hundreds of times per month and I go to the pull request every single time and never used the intermediate commit page one time, it would be great to have that as its own one-step feature :)

**Comment by eamodio** [comment]
@xster Can you go into more details into what you'd like to see?

**Comment by xster** [comment]
We can close this now, since the line blame decoration hover dialog now shows the GitHub PR link for the line.
