### ISSUE TITLE
Order matters for search filters in 'search commits'

### ISSUE THREAD

**Issue by mjbvz** [Axosoft/vscode-gitlens#1131]
Issue Type: <b>Bug</b>

**Repro**
1. Run the `Search Commits` command
1. Enter `search author:AUTHOR`
     - See search results
1. Now run the `Search Commits` command again
1. This time, swap the order of the two search terms: `author:AUTHOR search`
 
**Bug**
No results are returned in the second case

Extension version: 10.2.2
VS Code version: Code - Insiders 1.51.0-insider (74ef0a92fe8be7034d7d5f513e31262ab77d3bf1, 2020-10-19T05:48:39.773Z)
OS version: Darwin x64 19.6.0

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
