### ISSUE TITLE
Add a `--no-commit` option to merge command in the Git Command Palette

### ISSUE THREAD

**Issue by eamodio** [Axosoft/vscode-gitlens#1178]

**Comment by eamodio** [comment]
https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-commit

**Comment by GoluffyxD** [comment]
Hey can I work on this issue?

**Comment by eamodio** [comment]
@GoluffyxD please do!

**Comment by MatthewS2077** [comment]
Thanks for GitLens! 👍  

This would be a great option! 🤞

Is it easy to add a _--no-commit_ option to the GitLens settings? 

By default I never want to automatically commit after a non-conflicting merge.

**Comment by eamodio** [comment]
@GoluffyxD, @MatthewS2077, and others.

Do you just want a `--no-commit` option or a combined `--no-ff --no-commit` option like @dimaulupov's PR. Trying to gauge interest and understand use-cases.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by dimaulupov** [comment]
@eamodio Works great, just tested! 
Thank you very much! 🎉

**Comment by eamodio** [comment]
Thank you! 🙏
