### ISSUE TITLE
Try to guess ADO pull request autolinks based on commit message

### ISSUE THREAD

**Issue by markjm** [Axosoft/vscode-gitlens#1486]
When merging a pull request in Azure Devops, the default merge message will look like so

![image](https://user-images.githubusercontent.com/16494982/116594702-5d332500-a8d7-11eb-88ae-820c66f46cb6.png)

It would be great if we could auto-detect the `Merged PR` message and autolink this to open the correct PR. For non-default messages, this would no-op.

**Comment by markjm** [comment]
@eamodio wondering if youve had a chance to look at this. I think its a pretty low-hanging fruit for most ADO users

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
