### ISSUE TITLE
Avatars are blurry on retina displays

### ISSUE THREAD

**Issue by tomparkp** [Axosoft/vscode-gitlens#1511]
Avatars are blurry on retina displays:

<img width="65" alt="CleanShot 2021-05-17 at 17 10 56@2x" src="https://user-images.githubusercontent.com/2266762/118571478-fe710680-b732-11eb-837c-4e268a13de41.png">

**Comment by adaex** [comment]
Can anyone take the time to solve it? 🙏🙏🙏
