### ISSUE TITLE
treeview started as closed need another refresh (or re-opening) to show content

### ISSUE THREAD

**Issue by boltex** [Axosoft/vscode-gitlens#1582]
Issue Type: <b>Bug</b>

Hi! I've noticed a problem that i can also reproduce with the gitlens default extension in vscode. 

Make sure the 'commits' section of gitlens is closed when closing vscode. (and close vscode)

Restart vscode, goto the git lens view, open the commit tree view. Notice it's empty.

You'll have to hit the 'refresh icon' on the right of its title bar to populate it correctly. This was not the case a couple weeks ago.

(Thanks for your great product!!)

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.7.1-050701-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2851)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.54GB (0.82GB free)|
|Process Argv|--unity-launch --crash-reporter-id 21723db9-c8ea-462f-a1b4-f9c26cd3f8a8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
theme-verdandi|be5|2.0.1
leointeg|bol|0.1.16
bracket-pair-colorizer-2|Coe|0.2.1
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.42.1
vscode-eslint|dba|2.1.23
xml|Dot|2.5.1
gitlens|eam|11.6.0
tsl-problem-matcher|eam|0.4.0
prettier-vscode|esb|8.0.1
php-intellisense|fel|2.3.14
vscode-pull-request-github|Git|0.28.0
todo-tree|Gru|0.0.213
vscode-power-mode|hoo|2.2.0
rest-client|hum|0.24.5
svg|joc|1.4.9
git-graph|mhu|1.30.0
ecdc|mit|1.4.0
python|ms-|2021.6.944021595
vscode-pylance|ms-|2021.7.4
cpptools|ms-|1.5.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4583
debugger-for-chrome|msj|4.12.12
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.8.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
code-spell-checker|str|1.10.2
selectline-statusbar|tom|0.0.2
errorlens|use|3.3.1
vscodeintellicode|Vis|1.2.14
expand-selection-to-scope|vit|0.2.0
vscode-icons|vsc|11.5.0

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by eamodio** [comment]
This was fixed in the latest version of VS Code.
