### ISSUE TITLE
Should hide the context menu on unrelated tabs.

### ISSUE THREAD

**Issue by tamuratak** [Axosoft/vscode-gitlens#1583]
- GitLens Version: 11.6.0
- Git Version: git version 2.21.1 (Apple Git-122.3)

Version: 1.59.0-insider
Commit: b805d2e94937976bb17d0439f57fcd3a9d423c31
Date: 2021-07-20T05:12:13.059Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open Settings Panel.
2. Right-click the tab of the panel.
3. GitLens context menus appear.

We should hide the context menu on unrelated tabs.

![スクリーンショット 2021-07-21 14 56 37](https://user-images.githubusercontent.com/10665499/126438486-bc48b884-ef54-4ea3-9826-7f1a3ba17f0d.png)

I think it is enough to add `isFileSystemResource` to when clauses. I would make a PR if it would be acceptable.

```diff
--- a/package.json
+++ b/package.json
@@ -6752,39 +6752,39 @@
                        "editor/title/context": [
                                {
                                        "command": "gitlens.copyRemoteFileUrlWithoutRange",
-                                       "when": "gitlens:enabled && gitlens:hasRemotes && config.gitlens.menus.editorTab.clipboard",
+                                       "when": "gitlens:enabled && gitlens:hasRemotes && config.gitlens.menus.editorTab.clipboard && isFileSystemResource",
                                        "group": "1_cutcopypaste@100"
                                },
                                {
                                        "submenu": "gitlens/editor/changes",
-                                       "when": "gitlens:enabled && config.gitlens.menus.editorTab.compare",
+                                       "when": "gitlens:enabled && config.gitlens.menus.editorTab.compare && isFileSystemResource",
                                        "group": "2_gitlens@0"
                                },
```

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
