### ISSUE TITLE
Hover on blame can duplicate

### ISSUE THREAD

**Issue by tamuratak** [Axosoft/vscode-gitlens#1587]
- GitLens Version: Version: 11.6.0
- Git Version: git version 2.21.1 (Apple Git-122.3)

Version: 1.59.0-insider
Commit: e8a59bc6f920e731b47f0bc72263e82aba8b796e
Date: 2021-07-22T05:13:00.851Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 18.7.0
Steps to Reproduce:

1. Click `Toggle File Blame`
2. Hover on a line
3. Click `Open Blame prior to this change`
4. Hover on a line

The content of the hover duplicates.

![スクリーンショット 2021-07-24 18 58 43](https://user-images.githubusercontent.com/10665499/126865015-0a3c599c-e51b-42fb-ade8-203e688b630d.png)

The cause would be that `GutterBlameAnnotationProvider.onProvideAnnotation` is called multiple times. Then, `this.registerHoverProviders` is called multiple times.

https://github.com/eamodio/vscode-gitlens/blob/f6355932b33ccb6d65c8fab9875eddf60789915d/src/annotations/gutterBlameAnnotationProvider.ts#L32

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
