### ISSUE TITLE
X.globalState.setKeysForSync is not a function

### ISSUE THREAD

**Issue by slavik-lvovsky** [Axosoft/vscode-gitlens#1609]
- GitLens Version: 11.6.0
- Git Version: Run 2.20.1
- Theia Version: 1.14.0
- OS Version: Windows/MAC , All browsers

On the extension activate I get this error:
Activating extension 'GitLens — Git supercharged' failed: X.globalState.setKeysForSync is not a function

Theia version 1.14.0 still does not support vscode API setKeysForSync 

We in SAP want to integrate your extension in our webide based on theia 1.14.0
The extension fails.

I will prepare a PR that can fix/eliminate the issue

**Comment by slavik-lvovsky** [comment]
Hi @eamodio, @rebornix and @arrpee ,

We have a client who wants to use this extension in Theia 1.14.0.
Will you be able to review the provided fix for the issue ? https://github.com/eamodio/vscode-gitlens/pull/1610

Regards,
Slavik.

**Comment by rimasirich** [comment]
Hello @eamodio,
I experience the same issue as well. I would really appreciate if you could have a look on it.
Thank you in advance,
Rima

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
