### ISSUE TITLE
gitlens do operations， status bar（from left tor ight）running long time

### ISSUE THREAD

**Issue by huanghx1990** [Axosoft/vscode-gitlens#1664]
- GitLens Version:
- Git Version: Run `git --version`

- VSCode Version: Run `code --version`
- OS Version:
OS：centos7
vscode: 1.51.1
gitlens：1.11.0
git：2.30.2

gitlens in vscode(linux) do operation(as: stash pull， push， stage) in SourceControl side bar, the satus bar （moving from left to right use long time，thus not know whether the operation finished or not。 Is it any other configurations for speed up operations or do further debugging？

addtionaly， the stash operaton is much more slow since any interactive not show when i sel stash.

unfortunately，it base on project to Reproduce:

**Comment by eamodio** [comment]
@huanghx1990 @luxifr Can one of you provide some more details about where you are seeing things take a long time? A Gif/video would be great. Thanks!
