### ISSUE TITLE
gitlens.remotes: ${repo} has '%2520' instead of '%20' for a space

### ISSUE THREAD

**Issue by NGLocanovic** [Axosoft/vscode-gitlens#1669]
Issue Type: <b>Bug</b>

- GitLens Version: v11.6.0
- Git Version: git version 2.29.2.windows.2

I configured our companies remote in gitlens settings:

```
"gitlens.remotes": [
		{
			"domain": "localserver",
			"type": "Custom",
			"name": "localserver",
			"protocol":"https",
			"urls": {
				"repository": "https://localserver/${repo}",
				"branches": "https://localserver/${repo}/branches",
				"branch": "https://localserver/${repo}?version=GB${branch}",
				"commit": "https://localserver/${repo}/commit/${id}",
				"file": "https://localserver/${repo}?path=/${file}",
				"fileInBranch": "https://localserver/${repo}?path=${file}&version=GB${branch}",
				"fileInCommit": "https://localserver/${repo}/commit/${id}?_a=compare&path=/${file}",
				"fileLine": "#L${line}",
				"fileRange": "#L${start}-L${end}"
			}
		}
	]
```
But when I want to open, lets say a branch on the remote the link looks like this:
`https://localserver/DefaultCollection/XXX%2520XXX/_git/DB?version=GBmaster`
instead of:
`https://localserver/DefaultCollection/XXX%20XXX/_git/DB?version=GBmaster`

When I manually remove the '25' from the url, it opens as aspected.

Extension version: 11.6.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by NGLocanovic** [comment]
Is there anything you need, to further track down the problem?

**Comment by eamodio** [comment]
I think I have all I need -- looks like a double encoding issue.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by rpodola** [comment]
For me it is working now, thank you :)

insiders edition v2021.11.1604

**Comment by eamodio** [comment]
Thank you!

**Comment by NGLocanovic** [comment]
Works like a charm! Thanks a lot!
