### ISSUE TITLE
SCM randomly switches over branches with multiple git repos

### ISSUE THREAD

**Issue by Dozorengel** [Axosoft/vscode-gitlens#1682]
- GitLens Version: 11.6.1
- Git Version: 2.25.1

- VSCode Version: 1.61.0
- OS Version: WIndows 11

Steps to Reproduce:

1. Open VSCode workspace with multiple git repositories (two or more).
2. Switch over the branches in the first or last repository. The branch name will be duplicated in the other repository.
3. Press refresh in different repos to see random switching over the branches.
4. Type a commit message, then press refresh in the current git repo. The cursor will switch to the input in the other repository.

In some situation I can't switch to the necessary branch in specific repo as it shows me branches from the different repo. I have to randomly switching over the branches and repos, then this bug somehow resolves.
This bug came out not long ago and it appears both in windows 10 and 11. It also appears in my several workspaces, so it isn't a particular bug with one of my workspaces.
I attached a screencast as well.
https://skr.sh/vAU6ukGVrHs

**Comment by eamodio** [comment]
This is an issue with VS Code, not GitLens, so closing.
