### ISSUE TITLE
Gitlens randomly changes text box when entering a commit message

### ISSUE THREAD

**Issue by doc-E-brown** [Axosoft/vscode-gitlens#1686]
Issue Type: <b>Bug</b>

To reproduce the issue:

1. Have multiple repos open in the source code panel in VSCode.
2. Stage some files in one of the repos
3. Start entering a commit message in that repo

While writing the commit mesage VSCode / GitLens will automatically switch to a different text box for the commit message of a different repo.

Extension version: 11.6.1
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:02.929Z)
OS version: Linux x64 5.11.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2958)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|46.60GB (26.59GB free)|
|Process Argv|--unity-launch --crash-reporter-id 8489a535-5b1d-4bae-a1f5-786f4683af05|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis400:30381677
vsaa593:30376534
vssld246:30379911

```

</details>

**Comment by eamodio** [comment]
This is an issue with VS Code itself, not GitLens. Please open the issue on the vscode repository. Thanks!
