### ISSUE TITLE
Wrong github link when opening via #<number> in commit/pr messages.

### ISSUE THREAD

**Issue by sidharthv96** [Axosoft/vscode-gitlens#1689]
- GitLens Version:
- Git Version: Run `git --version`

- VSCode Version: Run `code --version`
- OS Version:

Steps to Reproduce:

1. Fork https://github.com/microsoft/TypeScript
2. Clone and open
3. Line https://github.dev/microsoft/TypeScript/blob/main/src/compiler/checker.ts#L32200 
4. OR Search for Top_level_await_expressions_are_only_allowed_when_the_module_option_is_set_to_es2022_esnext_system_or_nodenext_and_the_target_option_is_set_to_es2017_or_higher in checker.ts

<img width="994" alt="image" src="https://user-images.githubusercontent.com/10703445/137467505-1d539261-446d-4133-bc18-b59e84a97ade.png">

When clicking on these links, it opens the Fork's issue page, not the `Microsoft/Typescript` repo's, throwing a 404
<img width="193" alt="image" src="https://user-images.githubusercontent.com/10703445/137468033-ab4ebab9-7ce5-41f7-a021-055ca4eac97c.png">

**Comment by eamodio** [comment]
In order for the auto-linking to work properly, you'll need to see the "default" remote to use. From the _Remotes_ view (in the sidebar) right-click on the desired remote to the `https://github.com/microsoft/TypeScript` repository (or add a remote if you don't have one). That will tell GitLens to use that remote to resolve urls with.

Hope that helps!
