### ISSUE TITLE
GitLens delay is severe

### ISSUE THREAD

**Issue by jievince** [Axosoft/vscode-gitlens#1692]
- GitLens Version: v11.6.1
- Git Version:  2.21.3
- VSCode Version: 1.61.1
- OS Version: ferora 31

Gitlens has a severe delay, every time I made a code change, GitLens took a few minutes to react.

**Comment by eamodio** [comment]
@jievince @luxifr Can one of you provide some more details about where you are seeing this delay? A Gif/video would be great. Thanks!

**Comment by jievince** [comment]
> #1664

Sorry for the late reply.
![image](https://user-images.githubusercontent.com/38901892/145936006-0a3b594b-c5db-4068-a7d1-3590f666711a.png)

**Comment by jievince** [comment]
> #1664

I typed `git commit` on the terminal but the status bar of gitlens takes for a long time to know that the changes have been commited via the terminal
