### ISSUE TITLE
cherry-pick --no-commit

### ISSUE THREAD

**Issue by marcoSven** [Axosoft/vscode-gitlens#1693]
is it possible to add `--no-commit` option?

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.
