### ISSUE TITLE
Workitem Link (Hover ) for Repository (DevOps) with Blank is broken

### ISSUE THREAD

**Issue by SBiernat** [Axosoft/vscode-gitlens#1695]
- GitLens Version: v11.6.1
- Git Version: Run `git --version` 2.33.0.windows.2

- VSCode Version: Run `code --version`
- OS Version:
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. For Remote-Repositories with a blank in the Name , e.g. "CCO0 Main" the WorkItem Link is broken.
2. 
![image](https://user-images.githubusercontent.com/45194723/138477381-db0d124b-d09e-4ab2-9898-fa9306e04f4b.png)

The displayed Link is 
https://dev.azure.com/DEHAM-WID/BC/CCO0 Main/_workitems/edit/208 (with blank)
and it should be
https://dev.azure.com/DEHAM-WID/BC/CCO0%20Main/_workitems/edit/208 (with masked blank)

I have looked at the Debug Log, and tried to find the problem within the logs. 
But i have not found any issue in there. So it seems, that the link is created and not logged.
Perhaps in the autolinks.ts???

Debug Log:
[2021-10-22 15:18:58:977] [c:/.../DEHAM-WID/CCO0 Main] git blame --root --incremental -- app/src/SCMFunctions.Codeunit.al • 241 ms 
[2021-10-22 15:19:01:559] [c:/.../DEHAM-WID/CCO0 Main] git ls-files -- app/src/SCMFunctions.Codeunit.al • 202 ms 
[2021-10-22 15:19:01:618] [c:/.../DEHAM-WID/CCO0 Main] git diff --no-ext-diff --minimal -U0 -M --diff-filter=M 039829a9dbd7f08e859cf8a49bc847b8f696ab1b -- app/src/SCMFunctions.Codeunit.al • 240 ms 
[2021-10-22 15:19:01:873] [c:/.../DEHAM-WID/CCO0 Main] git log --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -n3 -m --numstat --summary 49455f55ed032201d6a5f8d321a2fa734c14963b -- app/src/SCMFunctions.Codeunit.al • 311 ms

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). 

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by SBiernat** [comment]
Looks better
![image](https://user-images.githubusercontent.com/45194723/140466011-3bb43293-5155-49b3-b7d0-94fd5aef6c1e.png)
but don't fix the problem.

**Comment by SBiernat** [comment]
What kind of Infos do you need? I have answered, that it don't fix the problem and showed a screenshot .

**Comment by eamodio** [comment]
Sorry the bot was overzealous -- thanks for the info!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by SBiernat** [comment]
Hey Eric,
unfortunately the problem still exist with the insider Version 2021.11.1604 🙁

[cid:f94bc83b-3412-49b3-8c0b-89b3d29cf30f]
________________________________
Von: Eric Amodio ***@***.***>
Gesendet: Dienstag, 16. November 2021 05:39
An: Axosoft/vscode-gitlens ***@***.***>
Cc: Sven Biernat ***@***.***>; Author ***@***.***>
Betreff: Re: [Axosoft/vscode-gitlens] Workitem Link (Hover ) for Repository (DevOps) with Blank is broken (Issue #1695)


Closed #1695<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAxosoft%2Fvscode-gitlens%2Fissues%2F1695&data=04%7C01%7Csven.biernat%40cosmoconsult.com%7Cf6b3a07b960c447bff7c08d9a8bb1ea8%7C94d30528464f45a5a95e816428f57b90%7C0%7C0%7C637726343895339576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5XhZSyQfMqjEl2lLAmP1E%2BBNTpF6x4x8yKbNOgyjJsw%3D&reserved=0>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAxosoft%2Fvscode-gitlens%2Fissues%2F1695%23event-5622336002&data=04%7C01%7Csven.biernat%40cosmoconsult.com%7Cf6b3a07b960c447bff7c08d9a8bb1ea8%7C94d30528464f45a5a95e816428f57b90%7C0%7C0%7C637726343895349571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3a8U1LTWAuS0uKJLLY6xJ%2FUNFQxWMxGQFz2i1lxK2YA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKYZ3YZ44T2KC4QX2EWMLBDUMHOAPANCNFSM5GQ5LMTQ&data=04%7C01%7Csven.biernat%40cosmoconsult.com%7Cf6b3a07b960c447bff7c08d9a8bb1ea8%7C94d30528464f45a5a95e816428f57b90%7C0%7C0%7C637726343895349571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dwZz0M%2BA2RkiVqfnOwAbmZzagAikwiqhNybHfOWIK3A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csven.biernat%40cosmoconsult.com%7Cf6b3a07b960c447bff7c08d9a8bb1ea8%7C94d30528464f45a5a95e816428f57b90%7C0%7C0%7C637726343895359565%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JP4NZj%2FxTLKddAd0XC%2BzRBx1G12xRjtCNfpP%2FklCX2Y%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csven.biernat%40cosmoconsult.com%7Cf6b3a07b960c447bff7c08d9a8bb1ea8%7C94d30528464f45a5a95e816428f57b90%7C0%7C0%7C637726343895359565%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UGDIAszZpk9ZG0YFpqLDf1BCfwD%2BX3JZ6N%2Bvl%2BLrGz0%3D&reserved=0>.
 
Sven Biernat
Senior Consultant
 

COSMO CONSULT GmbH
Friesenweg 4, Marzipanfabrik Haus 14
22763 Hamburg

Teams  ***@***.*** 
Mobil +49 15222623448  
E-Mail  ***@***.*** 
Web  www.cosmoconsult.com 

https://de.cosmoconsult.com/COSMO CONSULT GmbH | Geschäftsführer: Klaus Aschauer | Sitz der Gesellschaft: Friesenweg 4 Marzipanfabrik Haus 14, 22763 Hamburg, Deutschland | Handelsregister: Hamburg HRB-119283 | USt-ID: DE815299984
Denken Sie nach, bevor Sie drucken. #COSMOgoesgreen

Business-Software für MenschenBitte prüfen Sie dem Umweltschutz zuliebe, ob das Ausdrucken dieser E-Mail wirklich notwendig ist. #COSMOgoesgreen

Business-Software für Menschen

**Comment by SBiernat** [comment]
Do i have to open a new ticket?

**Comment by eamodio** [comment]
@SBiernat 😢 sorry. Thank you -- I'll dig further into it.

**Comment by eamodio** [comment]
@SBiernat Can you give this one more try with tomorrow's GitLens insiders edition? I think it's really fixed now. Thanks!

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by SBiernat** [comment]
Looks good, thank you
![image](https://user-images.githubusercontent.com/45194723/142600405-e923cdd8-79e4-45c4-9ab4-2ca97408ecef.png)
