### ISSUE TITLE
Add open file action under comparison section within repositories view?

### ISSUE THREAD

**Issue by eamodio** [Axosoft/vscode-gitlens#1710]
### Discussed in https://github.com/Axosoft/vscode-gitlens/discussions/1709

<div type='discussions-op-text'>

<sup>Originally posted by **divnych** November  2, 2021</sup>
Hi. Is it possible to add **open file** button under the comparison section within the repositories view?

I mean the same one you may find under the branches section when hovering over a file for expanded commit.

![image](https://user-images.githubusercontent.com/33792604/139937878-c7fdb614-e565-4dad-bf9b-a63ab795a07a.png)

I find myself often using this section "Compare Working Tree with _another branch_" when working on something. Clicking on a row with file name opens a comparison of that file with _another branch_, which is nice. But when I want to quickly open a file itself from there it takes an additional step to open the context menu and only then I can open the file. It would be nice to have open file action as well here.

![image](https://user-images.githubusercontent.com/33792604/139942215-dd5c46c9-2c58-4f5e-bb20-e20fe3ea723d.png)

If It's already possible to do so, please explain me how. Thank you.</div>

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by divnych** [comment]
@eamodio It works now. Thank you.

**Comment by eamodio** [comment]
Awesome! Thank you!
