### ISSUE TITLE
GitHub Releases are not publishing

### ISSUE THREAD

**Issue by filiptronicek** [Axosoft/vscode-gitlens#1723]
Hello to the team @ Axosoft! 

I'm currently trying to fix up some regressions in OpenVSX, the vendor neutral marketplace for VS Code extensions. It looks like ~1 month ago the script for publishing new releases to GitHub broke [[1]](https://github.com/Axosoft/vscode-gitlens/runs/3839545232?check_suite_focus=true#step:8:9). 

I mostly wanted to bring this issue to your attention, but I would really appreciate if you could think about publishing this extension to the OpenVSX registry yourselves (basically get a token and add one command to your CI process, docs about that here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions), so that projects like OpenVSCode Server, VSCodium or code-server could leverage the latest updates to this extension no matter what.

**Comment by eamodio** [comment]
This should be fixed now
