### ISSUE TITLE
Gitlens don't startup.

### ISSUE THREAD

**Issue by JesseRobot1** [Axosoft/vscode-gitlens#1724]
When i try something with gitlens for example open settings i get the error:  command 'gitlens Open Settings' result in an error (command 'gitlens.showSettingPage' not found)
Gitlens does works on my linux pc

os: Windows 10 21H1
vscode version: 1.62.2
gitLens version: 11.6.1

Does someone have this problem too?

**Comment by eamodio** [comment]
Can you open the VS Code developer tools `Toggle Developer Tools` from the command palette and see if there are any errors in the console? And if so, can you post a screenshot here?

It might be similar to: https://github.com/microsoft/vscode/issues/136537

**Comment by JesseRobot1** [comment]
@eamodio  here it is
![image](https://user-images.githubusercontent.com/91422501/142205957-f7e698e8-dc3a-423f-bef7-0d1b2a973925.png)

**Comment by JesseRobot1** [comment]
i was just in the get started and found thad i need to install git
then gitlens does work!
