### ISSUE TITLE
SEARCH & COMPARE forgets comparisons on editor reload or change folder

### ISSUE THREAD

**Issue by BillDenton** [Axosoft/vscode-gitlens#1733]
- GitLens Version: v11.7.0
- Git Version: git version 2.29.2.windows.3

- VSCode Version: 1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
- OS Version: OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a comparison in SEARCH & COMPARE
2. "Developer: Reload Window" or close the window or open another folder & open the original folder.
3. The comparison created in step 1 is no longer present. Expect it to be remembered.

**Comment by eamodio** [comment]
If you "Pin" (via the pin icon on the item in the view) the search/comparison it will be remembered on a reload. Hope that helps!

**Comment by BillDenton** [comment]
@eamodio That certainly helps, but I have to remember to do that all the time. It would be easier if the GUI remembered its state similar to VS Code itself.

**Comment by eamodio** [comment]
@BillDenton OK, I'll change this into a feature request -- to add an option to make pinning be enabled by default.
