### ISSUE TITLE
Support Gerrit like urls for remotes

### ISSUE THREAD

**Issue by chun-wang** [Axosoft/vscode-gitlens#720]
Need tokens like changes、changeId、patch set for remotes url config

**Comment by eamodio** [comment]
I'm not at all familiar with Gerrit, but I would welcome a PR for this.

**Comment by andrewsavage1** [comment]
I'm willing to pick this up, but I'm curious what Gerrit-specific features people are actually interested in—i.e. patch sets seem like a strange thing to integrate into gitlens imo.

Supporting the basics like Change Ids would be pretty simple though.

**Comment by andrewsavage1** [comment]
I'll start with implementing basic support:
* Adding Gerrit as a supported type extending `RemoteProvider` with `GerritRemote`
* Being able to recognize and link Change Ids in the commit body

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by heartacker** [comment]
@chun-wang could you please tell us a simple SOP how to work with gerrit.

**Comment by andrewsavage1** [comment]
@eamodio Sorry I missed this, I'll verify it tomorrow.

**Comment by andrewsavage1** [comment]
I've verified that this is working as expected in the Gitlens insiders edition!

**Comment by eamodio** [comment]
Thank you!
